version: "3"

networks:
  infura:

services:
  mysql:
    restart: always
    image: mysql:5.7.22
    container_name: mysql-vhr
    ports:
      - 3306:3306
    environment:
      TZ: 'Asia/Taipei'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: '123'
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    volumes:
      - vhr-mysql-data:/var/lib/mysql
    networks:
      - infura
    restart: always
  redis:
    image: redis:3.2
    volumes:
      - ../redis/redis.conf:/etc/redis/redis.conf:ro
      - ../redis/data:/data
    command:
      - redis-server
      - /etc/redis/redis.conf
    ports:
      - 6379:6379
    restart: always
    networks:
      - infura
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "4369:4369"
      - "5671:5671"
      - "25672:25672"
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 123
      RABBITMQ_NODENAME: rabbitmq
      RABBITMQ_ERLANG_COOKIE: CURIOAPPLICATION
    networks:
      - infura

volumes:
  vhr-mysql-data: