spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123
    url: jdbc:mysql://mysql-vhr:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Taipei
  rabbitmq:
    username: root
    password: 123
    host: rabbitmq-vhr
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: redis-vhr
    database: 0
    port: 6379
    password: 123
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://fastdfs-tracker/